name = "mica"
version = "0.1.0"
defaultTargets = ["mica"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "13214706190da5a7c4f634733c8895396cb0a121"

# Libraries

[[lean_lib]]
name = "Mica"

# Executables

[[lean_exe]]
name = "mica"
root = "Main"

[[lean_exe]]
name = "frontend"
root = "Mica.Frontend.Main"

# Exploration (not built by default)

[[lean_lib]]
name = "Exploration"
globs = ["Exploration.+"]

[[lean_exe]]
name = "dynamic-goal"
root = "Exploration.DynamicGoal"

[[lean_exe]]
name = "smt-query"
root = "Exploration.SMTQuery"
