import Mica.Engine.Strategy

/-! ## ScopedM: The SMT Monad

Continuation-based monad over SMT operations. No raw push/pop — scoping
is handled exclusively by `bracket`. Each constructor except `ret` and `bracket`
corresponds to a single SMT command with a continuation receiving the response. -/

inductive ScopedM : Type → Type 1 where
  | ret : α → ScopedM α
  | declareConst : String → Srt → (Unit → ScopedM α) → ScopedM α
  | assert : Formula → (Unit → ScopedM α) → ScopedM α
  | checkSat : (SmtResult → ScopedM α) → ScopedM α
  | bracket : ScopedM β → (β → ScopedM α) → ScopedM α

/-! ## translate: ScopedM → Strategy -/

def ScopedM.translate : ScopedM α → Strategy α
  | .ret a => .done a
  | .declareConst n s k => .exec (.declareConst n s) (fun r => translate (k r))
  | .assert e k => .exec (.assert e) (fun r => translate (k r))
  | .checkSat k => .exec .checkSat (fun r => translate (k r))
  | .bracket body k =>
      .exec .push (fun () =>
        (translate body).bind (fun x =>
          .exec .pop (fun () => translate (k x))))

/-! ## Flat Context

A flat (non-stacked) view of the SMT state: just declarations and assertions.
The stacked SmtState is an implementation detail of the Strategy layer. -/

structure FlatCtx where
  decls : Signature
  asserts : Context

namespace FlatCtx

def empty : FlatCtx := ⟨Signature.empty, []⟩

def addDecl (ctx : FlatCtx) (n : String) (sort : Srt) : FlatCtx :=
  ⟨ctx.decls.addVar ⟨n, sort⟩, ctx.asserts⟩

def addAssert (ctx : FlatCtx) (φ : Formula) : FlatCtx :=
  ⟨ctx.decls, φ :: ctx.asserts⟩

end FlatCtx

/-- Flatten an SmtState by collecting all declarations and assertions across frames. -/
def SmtState.flatten (s : SmtState) : FlatCtx :=
  ⟨s.allDecls, s.allAsserts⟩

theorem SmtState.flatten_addDecl (s : SmtState) (v : Var) :
    (s.addDecl v).flatten = s.flatten.addDecl v.name v.sort := by
  simp only [SmtState.flatten, SmtState.allDecls, SmtState.allAsserts,
             SmtState.addDecl, FlatCtx.addDecl]
  cases s.frames with
  | nil => simp [Signature.addVar]
  | cons hd tl =>
    cases hd with
    | mk decls asserts =>
      cases decls
      simp [Signature.addVar, List.flatMap, List.cons_append]

theorem SmtState.flatten_addAssert (s : SmtState) (φ : Formula) :
    (s.addAssert φ).flatten = s.flatten.addAssert φ := by
  simp only [SmtState.flatten, SmtState.allDecls, SmtState.allAsserts,
             SmtState.addAssert, FlatCtx.addAssert]
  cases s.frames with
  | nil => rfl
  | cons hd tl => cases hd; simp [List.flatMap]

/-! ## Trace.PreservesFrames and translate_preservesFrames -/

/-- A trace preserves the stack tail and only extends the top frame. -/
def Trace.PreservesFrames (t : Trace α) (f : SmtFrame) (fs : List SmtFrame) : Prop :=
  ∃ f', f.Extends f' ∧ t.finalState ⟨f :: fs⟩ = ⟨f' :: fs⟩

/-- Traces generated by `translate m` preserve the stack: they only extend
    the top frame and leave deeper frames unchanged. -/
theorem ScopedM.translate_preservesFrames {m : ScopedM α} {f : SmtFrame} {fs : List SmtFrame}
    {t : Trace α} (hgen : Generates (translate m) t) :
    t.PreservesFrames f fs := by
  induction m generalizing f fs with
  | ret a =>
    cases hgen
    exact ⟨f, SmtFrame.Extends.refl f, rfl⟩
  | declareConst n s k ih =>
    cases hgen; rename_i rest resp hrest
    cases resp
    dsimp only at hrest
    have ⟨f', hext, hfin⟩ := ih () hrest
      (f := ⟨{ f.decls with vars := ⟨n, s⟩ :: f.decls.vars }, f.asserts⟩) (fs := fs)
    refine ⟨f', (SmtFrame.Extends.addDecl f ⟨n, s⟩).trans hext, ?_⟩
    simp [Trace.finalState, SmtState.step, SmtState.addDecl]; exact hfin
  | assert e k ih =>
    cases hgen; rename_i rest resp hrest
    cases resp
    dsimp only at hrest
    have ⟨f', hext, hfin⟩ := ih () hrest
      (f := ⟨f.decls, e :: f.asserts⟩) (fs := fs)
    refine ⟨f', (SmtFrame.Extends.addAssert f e).trans hext, ?_⟩
    simp [Trace.finalState, SmtState.step, SmtState.addAssert]; exact hfin
  | checkSat k ih =>
    cases hgen; rename_i rest resp hrest
    dsimp only at hrest
    have ⟨f', hext, hfin⟩ := ih resp hrest (f := f) (fs := fs)
    exact ⟨f', hext, by simp [Trace.finalState, SmtState.step]; exact hfin⟩
  | bracket body k ih_body ih_k =>
    simp only [translate] at hgen
    cases hgen; rename_i rest_outer hgen_outer
    dsimp only at hgen_outer
    obtain ⟨a, ts_body, tk_rest, hgen_body, hgen_cont, hres_body, hfin_bind, hres_bind⟩ :=
      Strategy.bind_generates_decompose hgen_outer
    cases hgen_cont; rename_i tk_k hgen_k
    dsimp only at hgen_k
    have hpf_body := @ih_body ⟨Signature.empty, []⟩ (f :: fs) ts_body hgen_body
    obtain ⟨fbody, _, hfin_body⟩ := hpf_body
    have hpf_k := ih_k a hgen_k (f := f) (fs := fs)
    obtain ⟨f', hext_k, hfin_k⟩ := hpf_k
    refine ⟨f', hext_k, ?_⟩
    simp only [Trace.finalState, SmtState.step, SmtState.push]
    rw [hfin_bind]
    simp only [hfin_body, Trace.finalState, SmtState.step, SmtState.pop]
    exact hfin_k

/-! ## ScopedM.eval: Extensional Semantics with Flat Contexts

`ScopedM.eval m ctx Φ` wraps Strategy.eval with flattening: the user works with
FlatCtx, and the stacked SmtState is existentially hidden. -/

def ScopedM.eval (m : ScopedM α) (ctx : FlatCtx) (ret : α) (ctx' : FlatCtx) : Prop :=
  ∃ st st', st.flatten = ctx ∧ st'.flatten = ctx'
  ∧ Strategy.eval (translate m) st ret st'

/-! ## Correspondence -/

theorem ScopedM.strategy_eval_initial_implies_ScopedM_eval {m : ScopedM α} {ret : α} {st' : SmtState} :
    Strategy.eval (translate m) .initial ret st' →
    ScopedM.eval m .empty ret st'.flatten := by
  intro h
  exact ⟨.initial, st', rfl, rfl, h⟩

/-! ## Inversion Lemmas -/

theorem ScopedM.eval_ret {a : α} {ctx : FlatCtx} {ret : α} {ctx' : FlatCtx} :
    ScopedM.eval (.ret a) ctx ret ctx' ↔ (ret = a ∧ ctx' = ctx) := by
  unfold ScopedM.eval translate
  constructor
  · rintro ⟨st, st', hflat, hflat', heval⟩
    rw [Strategy.eval_done] at heval
    exact ⟨heval.1, by rw [← hflat, ← hflat', heval.2]⟩
  · rintro ⟨rfl, rfl⟩
    exact ⟨⟨[⟨ctx'.decls, ctx'.asserts⟩]⟩, ⟨[⟨ctx'.decls, ctx'.asserts⟩]⟩,
      by simp [SmtState.flatten, SmtState.allDecls, SmtState.allAsserts],
      by simp [SmtState.flatten, SmtState.allDecls, SmtState.allAsserts],
      Strategy.eval_done.mpr ⟨rfl, rfl⟩⟩

theorem ScopedM.eval_declareConst {n : String} {s : Srt}
    {k : Unit → ScopedM α} {ctx : FlatCtx} {ret : α} {ctx' : FlatCtx} :
    ScopedM.eval (.declareConst n s k) ctx ret ctx' →
      ScopedM.eval (k ()) (ctx.addDecl n s) ret ctx' := by
  simp only [ScopedM.eval, translate, Strategy.eval]
  rintro ⟨st, st', hflat, hflat', t, hgen, hsound, hst', hret⟩
  cases hgen; rename_i rest resp hrest
  cases resp
  simp only [Trace.finalState, SmtState.step, Trace.result] at hsound hst' hret
  refine ⟨st.addDecl ⟨n, s⟩, st', ?_, hflat', rest, hrest, hsound, hst', hret⟩
  simp only [SmtState.flatten_addDecl, hflat]

theorem ScopedM.eval_assert {e : Formula}
    {k : Unit → ScopedM α} {ctx : FlatCtx} {ret : α} {ctx' : FlatCtx} :
    ScopedM.eval (.assert e k) ctx ret ctx' →
      ScopedM.eval (k ()) (ctx.addAssert e) ret ctx' := by
  simp only [ScopedM.eval, translate, Strategy.eval]
  rintro ⟨st, st', hflat, hflat', t, hgen, hsound, hst', hret⟩
  cases hgen; rename_i rest resp hrest
  cases resp
  simp only [Trace.finalState, SmtState.step, Trace.result] at hsound hst' hret
  refine ⟨st.addAssert e, st', ?_, hflat', rest, hrest, hsound, hst', hret⟩
  rw [SmtState.flatten_addAssert, hflat]

theorem ScopedM.eval_checkSat {k : SmtResult → ScopedM α} {ctx : FlatCtx} {ret : α} {ctx' : FlatCtx} :
    ScopedM.eval (.checkSat k) ctx ret ctx' →
      (¬ Satisfiable ctx.decls ctx.asserts ∧ ScopedM.eval (k .unsat) ctx ret ctx')
      ∨ ScopedM.eval (k .sat) ctx ret ctx'
      ∨ ScopedM.eval (k .unknown) ctx ret ctx' := by
  simp only [ScopedM.eval, translate, Strategy.eval]
  rintro ⟨st, st', hflat, hflat', t, hgen, hsound, hst', hret⟩
  cases hgen; rename_i rest resp hrest
  dsimp only at hrest
  simp only [Trace.finalState, SmtState.step, Trace.result] at hst' hret
  cases resp with
  | sat => right; left; exact ⟨st, st', hflat, hflat', rest, hrest, hsound, hst', hret⟩
  | unsat =>
    left
    have hunsat := hsound.1
    have : ctx.decls = st.allDecls ∧ ctx.asserts = st.allAsserts := by
      rw [← hflat]; exact ⟨rfl, rfl⟩
    rw [this.1, this.2]
    exact ⟨hunsat, st, st', hflat, hflat', rest, hrest, hsound.2, hst', hret⟩
  | unknown => right; right; exact ⟨st, st', hflat, hflat', rest, hrest, hsound, hst', hret⟩

theorem ScopedM.eval_bracket {body : ScopedM β} {k : β → ScopedM α}
    {ctx : FlatCtx} {ret : α} {ctx' : FlatCtx} :
    ScopedM.eval (.bracket body k) ctx ret ctx' →
      ∃ b ctx_body, ScopedM.eval body ctx b ctx_body ∧ ScopedM.eval (k b) ctx ret ctx' := by
  simp only [ScopedM.eval, translate, Strategy.eval]
  -- Forward: decompose bracket trace into body + k
  rintro ⟨st, st', hflat, hflat', t, hgen, hsound, hst', hret⟩
  -- t = .step .push () bind_trace where bind_trace is (translate body).bind (...)
  cases hgen; rename_i bind_trace _ hgen_bind
  dsimp only at hgen_bind
  have hsound_inner : TraceSound st.push bind_trace := hsound
  -- Decompose the bind trace
  obtain ⟨a, ts_body, tk_rest, hgen_body, hgen_cont, hres_body, hsound_body, hsound_rest,
          hfin_bind, hres_bind⟩ :=
    Strategy.bind_traceSound hgen_bind hsound_inner
  cases hgen_cont; rename_i tk_k _ hgen_k
  dsimp only at hgen_k
  -- Frame preservation: body only extends the pushed frame
  obtain ⟨fbody, _, hfin_body⟩ := @translate_preservesFrames _ body
    (f := ⟨Signature.empty, []⟩) (fs := st.frames) (t := ts_body) hgen_body
  refine ⟨ts_body.result, (ts_body.finalState st.push).flatten, ?_, ?_⟩
  · -- Witness for body: st.push (flattens to ctx)
    refine ⟨st.push, ts_body.finalState st.push, ?_, rfl, ts_body, hgen_body, hsound_body, rfl, rfl⟩
    simp [SmtState.push, SmtState.flatten, SmtState.allDecls, SmtState.allAsserts, ← hflat]
  · -- After body: extract TraceSound for k from the pop step
    simp only [SmtState.push] at hsound_rest
    rw [hfin_body] at hsound_rest
    simp [TraceSound, SmtState.pop] at hsound_rest
    -- Simplify hst' through the full trace
    simp only [Trace.finalState, SmtState.step, SmtState.push] at hst'
    rw [hfin_bind, hfin_body] at hst'
    simp only [Trace.finalState, SmtState.step, SmtState.pop] at hst'
    -- Simplify hret
    simp only [Trace.result] at hret
    rw [hres_bind] at hret
    simp only [Trace.result] at hret
    rw [← hres_body] at hgen_k
    refine ⟨⟨st.frames⟩, st', ?_, hflat', tk_k, hgen_k, hsound_rest, hst', hret⟩
    cases st; exact hflat

/-! ## ScopedM.bind -/

/-- Bind for ScopedM, derived from the continuation structure. -/
def ScopedM.bind : ScopedM α → (α → ScopedM β) → ScopedM β
  | .ret a, k => k a
  | .declareConst n s cont, k => .declareConst n s (fun r => (cont r).bind k)
  | .assert e cont, k => .assert e (fun r => (cont r).bind k)
  | .checkSat cont, k => .checkSat (fun r => (cont r).bind k)
  | .bracket body cont, k => .bracket body (fun x => (cont x).bind k)

theorem ScopedM.translate_bind (m : ScopedM α) (k : α → ScopedM β) :
    translate (m.bind k) = (translate m).bind (fun a => translate (k a)) := by
  induction m with
  | ret a => simp [ScopedM.bind, translate, Strategy.bind]
  | declareConst n s cont ih =>
    simp only [ScopedM.bind, translate, Strategy.bind]; congr 1; funext r; exact ih r k
  | assert e cont ih =>
    simp only [ScopedM.bind, translate, Strategy.bind]; congr 1; funext r; exact ih r k
  | checkSat cont ih =>
    simp only [ScopedM.bind, translate, Strategy.bind]; congr 1; funext r; exact ih r k
  | bracket body cont _ ih_cont =>
    simp only [ScopedM.bind, translate, Strategy.bind]
    congr 1; funext ⟨⟩
    rw [Strategy.bind_assoc]
    congr 1; funext x
    simp only [Strategy.bind]
    congr 1; funext ⟨⟩
    exact ih_cont x k

/-- Bind decomposes into two sequential evaluations. -/
theorem ScopedM.eval_bind {m : ScopedM α} {k : α → ScopedM β}
    {ctx : FlatCtx} {ret : β} {ctx' : FlatCtx} :
    ScopedM.eval (m.bind k) ctx ret ctx' →
      ∃ a ctx_mid, ScopedM.eval m ctx a ctx_mid ∧ ScopedM.eval (k a) ctx_mid ret ctx' := by
  intro h
  simp only [ScopedM.eval, Strategy.eval] at h ⊢
  obtain ⟨st, st', hflat, hflat', t, hgen, hsound, hst', hret⟩ := h
  rw [translate_bind] at hgen
  -- Decompose the bind trace
  obtain ⟨a, ts, tk, hgen_s, hgen_k, hres_s, hsound_s, hsound_k, hfin, hresult⟩ :=
    Strategy.bind_traceSound hgen hsound
  refine ⟨a, (ts.finalState st).flatten, ?_, ?_⟩
  · exact ⟨st, ts.finalState st, hflat, rfl, ts, hgen_s, hsound_s, rfl, hres_s.symm⟩
  · refine ⟨ts.finalState st, st', rfl, hflat', tk, ?_, hsound_k, ?_, ?_⟩
    · subst hres_s; exact hgen_k
    · rw [← hfin, hst']
    · rw [← hresult, hret]


def FlatCtx.subset (Δ Δ': FlatCtx) :=
  Δ.decls.vars ⊆ Δ'.decls.vars ∧ Δ.asserts ⊆ Δ'.asserts

instance : HasSubset FlatCtx where
  Subset := FlatCtx.subset

theorem ScopedM.eval_extends {α} s Δ (r : α) Δ' :
  ScopedM.eval s Δ r Δ' → Δ ⊆ Δ' := by
  induction s generalizing Δ Δ' with
  | ret a =>
    intro h
    obtain ⟨rfl, rfl⟩ := ScopedM.eval_ret.mp h
    exact ⟨List.Subset.refl _, List.Subset.refl _⟩
  | declareConst n sort k ih =>
    intro h
    have h := ScopedM.eval_declareConst h
    have := ih () _ _ _ h
    exact ⟨fun x hx => this.1 (List.mem_cons_of_mem _ hx), this.2⟩
  | assert φ k ih =>
    intro h
    have h := ScopedM.eval_assert h
    have := ih () _ _ _ h
    exact ⟨this.1, fun x hx => this.2 (List.mem_cons_of_mem _ hx)⟩
  | checkSat k ih =>
    intro h
    rcases ScopedM.eval_checkSat h with ⟨_, h⟩ | h | h
    · exact ih .unsat _ _ _ h
    · exact ih .sat _ _ _ h
    · exact ih .unknown _ _ _ h
  | bracket body k ih_body ih_k =>
    intro h
    obtain ⟨b, ctx_body, _, hk⟩ := ScopedM.eval_bracket h
    exact ih_k b _ _ _ hk
